theme = "nord-night"

[editor]
line-number = "relative"
mouse = false
true-color = true
bufferline = "multiple"
auto-completion = true
path-completion = true
completion-timeout = 50
auto-format = true
soft-wrap.enable = true


[editor.whitespace.characters]
newline = "↴"
tab = "⇥"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]


[keys.normal.space.u]
f = ":format"
w = ":set whitespace.render all"
W = ":set whitespace.render none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
