#
# neix main "feeds" configuration
# ===============================
# 
# Example:
# TITLE = PROTOCOL://[username[:password]@]DOMAIN.TOP-LEVEL-DOMAIN
[neix] livny=https://www.youtube.com/feeds/videos.xml?channel_id=UClycXAqkbqZp_aO8rr7BmLQ
[neix] Alex Cowling=https://www.youtube.com/feeds/videos.xml?channel_id=UCGJ0qvvAON5Pog8hmzuouDQ
[neix] Boy Boy=https://www.youtube.com/feeds/videos.xml?channel_id=UC_S45UpAYVuc0fYEcHN9BVQ
[neix] Bread on Penguins=https://www.youtube.com/feeds/videos.xml?channel_id=UCwHwDuNd9lCdA7chyyquDXw
[neix] Chemdelic=https://www.youtube.com/feeds/videos.xml?channel_id=UCdMaCWu6jL1RxRppDocImOQ
[neix] Code Bullet=https://www.youtube.com/feeds/videos.xml?channel_id=UC0e3QhIYukixgh5VVpKHH9Q
[neix] DankPods=https://www.youtube.com/feeds/videos.xml?channel_id=UC7Jwj9fkrf1adN4fMmTkpug
[neix] Devon Larratt=https://www.youtube.com/feeds/videos.xml?channel_id=UCBcMvaSRmSh3362bzvOBerw
[neix] ebola=https://www.youtube.com/feeds/videos.xml?channel_id=UCBMj744GalEY5w4WRRH2f8g
[neix] ebola man=https://www.youtube.com/feeds/videos.xml?channel_id=UCFJOedcf0Op002r4S5UUESQ
[neix] Euro=https://www.youtube.com/feeds/videos.xml?channel_id=UC8Zxt9cwkrio05iDgdORE8A
[neix] FaceDev=https://www.youtube.com/feeds/videos.xml?channel_id=UCZ_cuJGBis0vi6U3bWmvDIg
[neix] Fireship=https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA
[neix] foci=https://www.youtube.com/feeds/videos.xml?channel_id=UCF3JCPvD72PJMVZrfST-fag
[neix] GhostStrats=https://www.youtube.com/feeds/videos.xml?channel_id=UCzSZPWtTRA4G946XRAn2XLQ
[neix] GhostStrats Sec=https://www.youtube.com/feeds/videos.xml?channel_id=UCFnTr4WVtZempr6u3PeYihw
[neix] Horses =https://www.youtube.com/feeds/videos.xml?channel_id=UCrx2zrPjhGRi9TwszZiLwEg
[neix] Ian Barseagle=https://www.youtube.com/feeds/videos.xml?channel_id=UCt7eSYUfe0JYq9L-eM-EDjw
[neix] jackedurden=https://www.youtube.com/feeds/videos.xml?channel_id=UC_c0uMyaYaHpIs9eLDsylIw
[neix] Jett Franzen=https://www.youtube.com/feeds/videos.xml?channel_id=UCRBMUySQ2syRKfqaBb7oVaw
[neix] jvscholz=https://www.youtube.com/feeds/videos.xml?channel_id=UCcaTUtGzOiS4cqrgtcsHYWg
[neix] Kevin Zhang=https://www.youtube.com/feeds/videos.xml?channel_id=UCuTXKOYkfNG6166srF95PJw
[neix] livny=https://www.youtube.com/feeds/videos.xml?channel_id=UClycXAqkbqZp_aO8rr7BmLQ
[neix] Loi Duong Jr.=https://www.youtube.com/feeds/videos.xml?channel_id=UCi0ga6IhUlGaghiLMgqxRtQ
[neix] Luke Smith=https://www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA
[neix] Magnus Midtbø=https://www.youtube.com/feeds/videos.xml?channel_id=UC_gSotrFVZ_PiAxo3fTQVuQ
[neix] Man in the Mayhem=https://www.youtube.com/feeds/videos.xml?channel_id=UCKgIe7A86cuoDn2pTo7Au7w
[neix] Masked Mediator=https://www.youtube.com/feeds/videos.xml?channel_id=UCV3IkfV87fHXLB07d3mIM5w
[neix] Mental Outlaw=https://www.youtube.com/feeds/videos.xml?channel_id=UC7YOGHUfC1Tb6E4pudI9STA
[neix] Outdoor Boys=https://www.youtube.com/feeds/videos.xml?channel_id=UCfpCQ89W9wjkHc8J_6eTbBg
[neix] Primal Lutay=https://www.youtube.com/feeds/videos.xml?channel_id=UCRRGdi_5c4zhyLIFByziAYw
[neix] Shannon Mclain=https://www.youtube.com/feeds/videos.xml?channel_id=UC3nCnROEmdMefaybAWYPKFw
[neix] Swhole Animal=https://www.youtube.com/feeds/videos.xml?channel_id=UCUfQ23SL-bXSF-dx8AzcjwQ
[neix] Sylvan Franklin=https://www.youtube.com/feeds/videos.xml?channel_id=UC04nROIJrY22Gl2aFqKcdqQ
[neix] Talking Sasquach=https://www.youtube.com/feeds/videos.xml?channel_id=UCUoJk48pujh29p8zLsnD5PQ
[neix] Techlore=https://www.youtube.com/feeds/videos.xml?channel_id=UCs6KfncB4OV6Vug4o_bzijg
[neix] THE BIG LEZ SHOW OFFICIAL=https://www.youtube.com/feeds/videos.xml?channel_id=UCV1G6JkQtB2nobFm3MGNsBQ
[neix] The Hated One=https://www.youtube.com/feeds/videos.xml?channel_id=UCjr2bPAyPV7t35MvcgT3W8Q
[neix] tony=https://www.youtube.com/feeds/videos.xml?channel_id=UC65_CVnMw6hvPET_DRDg3GA
