script-opts=ytdl_hook-ytdl_path=yt-dlp

force-seekable=yes # If the player thinks that the media is not seekable, force enable seeking
keep-open=always # Don't close the player after finishing the video,
reset-on-next-file=pause


dither-depth=8                                  # This must be set to match your monitor's bit depth

# ==========    SCALERS AND SHADERS    ==========

#scale=ewa_lanczossharp                          # Luma upscaler
#dscale=mitchell                                 # Luma downscaler
#cscale=ewa_lanczossharp                         # Chroma up&downscaler
gpu-shader-cache-dir='~/shaders/cache'         # https://mpv.io/manual/stable/#options-gpu-shader-cache-dir


# ==========    ON SCREEN DISPLAY AND ON SCREEN CONTROLLER    ==========

osd-bar=no                                      # Don't show a huge volume box on screen when turning the volume up/down
osc=no                                          # Allows for custom OSC to be used  https://github.com/cyl0/mpv-osc-morden-x
border=no                                       # Optional for modern OSC, but recommended
cursor-autohide-fs-only=yes                     # If this option is given, the cursor is always visible in windowed mode
                                                # In fullscreen mode, the cursor is shown or hidden according to --cursor-autohide
cursor-autohide=300                             # Cursor hide in ms   
osd-level=1                                     # https://mpv.io/manual/stable/#options-osd-level
osd-duration=1000                               # Set the duration of the OSD messages in ms
hr-seek=yes                                     # Select when to use precise seeks that are not limited to keyframes
                                                # https://mpv.io/manual/stable/#options-hr-seek


# ==========    AUDIO    ==========

volume=100                                      # default volume, 100 = unchanged
audio-file-auto=fuzzy                           # Load external audio with (almost) the same name as the video
volume-max=200                                  # Max volume of the player
audio-pitch-correction=yes                      # https://mpv.io/manual/stable/#options-audio-pitch-correction


# ==========    SCREENSHOT    ==========

screenshot-format=png                           # Output format of screenshots
screenshot-high-bit-depth=yes                   # Same output bitdepth as the video. Set it "no" if you want to save disc space
screenshot-png-compression=1                    # Compression of the PNG picture (1-9).
                                                # Higher value means better compression, but takes more time
screenshot-directory="~/Pictures/mpv-screenshots"           # Output directory
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"             # Name format (filename-hour-minute-second-milisecond-number)



#[window_size_for_mp3_files]
#profile-desc="Sets window size for mp3 files to a fixed value"
#profile-cond=filename:match"[.]mp3$" ~= nil
#geometry=200x200


geometry=2300
