#!/bin/sh

# Gruvbox Dark (Hard) Color Palette
export COLOR_BACKGROUND=0xe01d2021
export COLOR_FOREGROUND=0xe0fbf1c7

export COLOR_ACCENT=0xe0d65d0e
export COLOR_ACCENT_BRIGHT=0xe0fe8019

export COLOR_BLACK=0xe031302f
export COLOR_RED=0xe0cc241d
export COLOR_GREEN=0xe098971a
export COLOR_YELLOW=0xe0d79921
export COLOR_BLUE=0xe0458588
export COLOR_MAGENTA=0xe0b16286
export COLOR_CYAN=0xe0689d6a
export COLOR_WHITE=0xe0fbf1c7

export COLOR_BLACK_BRIGHT=0xe03c3836
export COLOR_RED_BRIGHT=0xe0e85334
export COLOR_GREEN_BRIGHT=0xe079740e
export COLOR_YELLOW_BRIGHT=0xe0b57614
export COLOR_BLUE_BRIGHT=0xe0076678
export COLOR_MAGENTA_BRIGHT=0xe08f3f71
export COLOR_CYAN_BRIGHT=0xe0427b58
export COLOR_WHITE_BRIGHT=0xe0f4e7bd
export COLOR_BL=0xe0282828
export COLOR_BL2=0xe031302f

PLUGIN_DIR="$CONFIG_DIR/plugins"
source "$CONFIG_DIR/colors.sh" # Loads all defined colors

##### Bar Appearance #####
sketchybar --bar position=top height=37 blur_radius=30 color=$COLOR_BACKGROUND

##### Changing Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=$COLOR_FOREGROUND
  label.color=$COLOR_WHITE
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=7
    icon.padding_right=7
    background.color=$COLOR_BL2
    background.corner_radius=5
    background.height=25
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

##### Adding Left Items #####
sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off icon.color=$COLOR_ACCENT \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched \
           --add item yabai left \
           -- set yabai icon.drawing=off script="$PLUGIN_DIR/yabai.sh"

#### Adding Center Items ####  

sketchybar --add item spotify_prev center \
           --set spotify_prev icon= \
                           click_script="osascript -e 'tell application \"Spotify\" to previous track'"


sketchybar --add item spotify_label center \
           --set spotify_label script="$PLUGIN_DIR/spotify.sh" \
                        updates=on \
                        update_freq=5 \
                        click_script="osascript -e 'tell application \"Spotify\" to playpause'"

# Add next button
sketchybar --add item spotify_next center \
           --set spotify_next icon= \
                           click_script="osascript -e 'tell application \"Spotify\" to next track'"




##### Adding Right Items #####
sketchybar --add item yabai_layout right \
           --set yabai_layout icon.font="Hack Nerd Font:Bold:16.0" \
                              label.drawing=off \
                              script="$PLUGIN_DIR/yabai_layout.sh" \


sketchybar --add item clock right \
           --set clock update_freq=10 icon=  icon.color=$COLOR_ACCENT_BRIGHT script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" icon.color=$COLOR_GREEN \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" icon.color=$COLOR_YELLOW \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
