# reload source 
unbind r 
bind r source-file ~/.tmux.conf

#set-option -sa terminal-features ',iterm-256color:RGB'

#
unbind f 
bind j next-window
# rebind leader
set -g prefix C-f

# mouse support
set -g mouse on

# add vim bindings for window selection 
bind-key h select-pane -L 
#bind-key j select-pane -D 
bind-key k select-pane -U
bind-key l select-pane -R 

# status bar 
set -g status-position top 
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white  "
set -g window-status-current-style "fg=colour255,bg=default,bold"
set -g window-status-separator ""
set -g window-status-format "#[fg=colour240]#[default] #I:#W#{?window_flags,#{window_flags},} #[fg=colour240]#[default]"
set -g window-status-current-format "#[fg=colour252]#[default] #I:#W#{?window_flags,#{window_flags},} #[fg=colour252]#[default]"
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""


# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on


set-option -g allow-passthrough on
set-option -g escape-time 0


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
bind f run "tmux neww ~/.config/scripts/tmux-session-dispensary.sh"
bind p run "tmux neww ~/.config/scripts/open-pdf.sh"
bind g run "~/.config/scripts/open-github.sh"
#bind t run "tmux neww ~/.config/scripts/time.sh"
bind N run "~/.config/scripts/tmux-session-dispensary.sh ~/Documents/notes"
bind P run "~/.config/scripts/tmux-session-dispensary.sh ~/Documents/Projects"
bind R run "~/.config/scripts/tmux-session-dispensary.sh ~/Documents/repos"
bind D run "~/.config/scripts/tmux-session-dispensary.sh ~/.config"
bind H run "~/.config/scripts/tmux-session-dispensary.sh ~"
bind l run "~/.config/scripts/tmux-session-dispensary.sh ~/Downloads"
#bind S run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/projects/stormy"
bind y neww -n "nnn" -S nnn 
#bind O run "tmux neww ~/.config/scripts/links-picker.sh"
#bind e neww -S -n "LINKS" "nvim ~/.config/links.tsv"
bind E show-environment -g
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
